### ISSUE TITLE
ide-electron 首次编译成功，demo运行成功，但yarn run pack报错，详细如下

### ISSUE THREAD

**Issue by alex-jh-jiang** [opensumi/ide-electron#111]
D:\code\opensumi\ide-electron>yarn pack
yarn pack v1.22.22
success Wrote tarball to "D:\\code\\opensumi\\ide-electron\\ide-electron-v1.0.0.tgz".
Done in 7.40s.

D:\code\opensumi\ide-electron>yarn run pack
yarn run v1.22.22
$ yarn build-prod && node build/pack.js
$ rimraf -rf ./app && rimraf -rf ./out && run-p build-prod:*
$ webpack --config ./build/webpack.node.config.js --mode=production
$ webpack --config ./build/webpack.browser.config.js --mode=production
$ webpack --config ./build/webpack.main.config.js --mode=production
$ webpack --config ./build/webpack.extension-host.config.js --mode=production
$ webpack --config ./build/webpack.webview.config.js --mode=production
asset host-preload.js 9.65 KiB [emitted] [minimized] (name: main) 1 related asset
asset plain-preload.js 939 bytes [emitted] [from: node_modules/@opensumi/ide-webview/lib/electron-webview/plain-preload.js] [copied] [minimized]
modules by path ./node_modules/@opensumi/ide-webview/lib/electron-webview/*.js 2.02 KiB
  ./node_modules/@opensumi/ide-webview/lib/electron-webview/host-preload.js 54 bytes [built] [code generated]
  ./node_modules/@opensumi/ide-webview/lib/electron-webview/host-channel.js 1.96 KiB [built] [code generated]
modules by path ./node_modules/@opensumi/ide-webview/lib/webview-host/*.js 15.9 KiB
  ./node_modules/@opensumi/ide-webview/lib/webview-host/webview-manager.js 13.3 KiB [built] [code generated]
  ./node_modules/@opensumi/ide-webview/lib/webview-host/common.js 2.62 KiB [built] [code generated]
external "electron" 42 bytes [built] [code generated]
webpack 5.87.0 compiled successfully in 1886 ms
asset index.js 803 KiB [emitted] [minimized] (name: main) 1 related asset
asset 132.index.js 323 KiB [emitted] [minimized] (id hint: vendors)
runtime modules 3.17 KiB 7 modules
modules by path ./node_modules/ 2.09 MiB
  javascript modules 2.01 MiB 405 modules
  json modules 86.7 KiB
    ./node_modules/iconv-lite/encodings/tables/shiftjis.json 8.78 KiB [built] [code generated]
    ./node_modules/iconv-lite/encodings/tables/eucjp.json 15.1 KiB [built] [code generated]
    + 6 modules
modules by path ./src/ 18 KiB
  modules by path ./src/main/ 15.9 KiB
    modules by path ./src/main/*.ts 8.41 KiB 3 modules
    modules by path ./src/main/services/*.ts 7.46 KiB 3 modules
  modules by path ./src/common/ 2.11 KiB
    ./src/common/types.ts 238 bytes [built] [code generated]
    + 2 modules
+ 16 modules
webpack 5.87.0 compiled successfully in 56370 ms
asset index.js 2.46 MiB [emitted] [minimized] (name: main) 1 related asset
asset 967.index.js 342 KiB [emitted] [minimized] (id hint: vendors) 1 related asset
asset 132.index.js 323 KiB [emitted] [minimized] (id hint: vendors)
runtime modules 3.29 KiB 8 modules
modules by path ./node_modules/ 4.88 MiB
  javascript modules 4.07 MiB
    cacheable modules 4.07 MiB 1073 modules
    + 5 modules
  json modules 823 KiB 29 modules
modules by path ./src/ 13.3 KiB
  modules by path ./src/node/*.ts 9.11 KiB 3 modules
  modules by path ./src/modules/todo/ 1.94 KiB 3 modules
  modules by path ./src/common/ 1.88 KiB
    ./src/common/constants.ts 767 bytes [built] [code generated]
    ./src/common/node/utils.ts 1.13 KiB [built] [code generated]
  ./src/extensionManager/node.ts 336 bytes [built] [code generated]
+ 30 modules

WARNING in ./node_modules/@opensumi/ide-extension/lib/node/languagePack.js 292:25-32
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@opensumi/ide-extension/lib/node/extension.service.client.js 13:32-57
 @ ./node_modules/@opensumi/ide-extension/lib/node/index.js 11:35-72
 @ ./src/node/index.ts 12:15-58

WARNING in ./node_modules/chrome-remote-interface/node_modules/ws/lib/BufferUtil.js 35:21-42
Module not found: Error: Can't resolve 'bufferutil' in 'D:\code\opensumi\ide-electron\node_modules\chrome-remote-interface\node_modules\ws\lib'
Did you mean './bufferutil'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.
 @ ./node_modules/chrome-remote-interface/node_modules/ws/lib/Receiver.js 13:19-42
 @ ./node_modules/chrome-remote-interface/node_modules/ws/index.js 12:21-46
 @ ./node_modules/chrome-remote-interface/lib/chrome.js 7:18-31
 @ ./node_modules/chrome-remote-interface/index.js 6:15-41
 @ ./node_modules/v8-inspect-profiler/index.js 10:12-46
 @ ./node_modules/@opensumi/ide-extension/lib/node/extension.profiler.service.js 34:31-60
 @ ./node_modules/@opensumi/ide-extension/lib/node/index.js 9:37-76
 @ ./src/node/index.ts 12:15-58

WARNING in ./node_modules/chrome-remote-interface/node_modules/ws/lib/Validation.js 10:22-47
Module not found: Error: Can't resolve 'utf-8-validate' in 'D:\code\opensumi\ide-electron\node_modules\chrome-remote-interface\node_modules\ws\lib'
 @ ./node_modules/chrome-remote-interface/node_modules/ws/lib/Receiver.js 12:20-43
 @ ./node_modules/chrome-remote-interface/node_modules/ws/index.js 12:21-46
 @ ./node_modules/chrome-remote-interface/lib/chrome.js 7:18-31
 @ ./node_modules/chrome-remote-interface/index.js 6:15-41
 @ ./node_modules/v8-inspect-profiler/index.js 10:12-46
 @ ./node_modules/@opensumi/ide-extension/lib/node/extension.profiler.service.js 34:31-60
 @ ./node_modules/@opensumi/ide-extension/lib/node/index.js 9:37-76
 @ ./src/node/index.ts 12:15-58

WARNING in ./node_modules/vscode-languageserver-types/lib/umd/main.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@opensumi/ide-file-service/lib/node/file-service.js 7:38-76
 @ ./node_modules/@opensumi/ide-file-service/lib/node/index.js 10:23-48 11:21-46
 @ ./src/node/index.ts 6:15-61

WARNING in ./node_modules/ws/lib/buffer-util.js 117:23-44
Module not found: Error: Can't resolve 'bufferutil' in 'D:\code\opensumi\ide-electron\node_modules\ws\lib'
 @ ./node_modules/ws/lib/websocket.js 31:21-45
 @ ./node_modules/ws/index.js 3:18-44
 @ ./node_modules/@opensumi/ide-connection/lib/node/common-channel-handler.js 6:37-50
 @ ./node_modules/@opensumi/ide-connection/lib/node/index.js 5:21-56
 @ ./node_modules/@opensumi/ide-core-node/lib/connection.js 8:15-59
 @ ./node_modules/@opensumi/ide-core-node/lib/index.js 6:21-44
 @ ./src/node/index.ts 5:24-58

WARNING in ./node_modules/ws/lib/validation.js 122:24-49
Module not found: Error: Can't resolve 'utf-8-validate' in 'D:\code\opensumi\ide-electron\node_modules\ws\lib'
 @ ./node_modules/ws/lib/receiver.js 13:43-66
 @ ./node_modules/ws/index.js 7:21-46
 @ ./node_modules/@opensumi/ide-connection/lib/node/common-channel-handler.js 6:37-50
 @ ./node_modules/@opensumi/ide-connection/lib/node/index.js 5:21-56
 @ ./node_modules/@opensumi/ide-core-node/lib/connection.js 8:15-59
 @ ./node_modules/@opensumi/ide-core-node/lib/index.js 6:21-44
 @ ./src/node/index.ts 5:24-58

WARNING in ./node_modules/yargs/build/index.cjs 1:60883-60890
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/yargs/index.cjs 5:29-57
 @ ./src/node/server.ts 6:35-51
 @ ./src/node/index.ts 4:17-36

WARNING in ./node_modules/yargs/build/index.cjs 1:61275-61282
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/yargs/index.cjs 5:29-57
 @ ./src/node/server.ts 6:35-51
 @ ./src/node/index.ts 4:17-36

WARNING in ./node_modules/yargs/index.cjs 12:39-46
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./src/node/server.ts 6:35-51
 @ ./src/node/index.ts 4:17-36

9 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.87.0 compiled with 9 warnings in 94251 ms
asset index.js 2.56 MiB [emitted] [minimized] (name: main) 1 related asset
asset 132.index.js 323 KiB [emitted] [minimized] (id hint: vendors)
runtime modules 3.29 KiB 8 modules
modules by path ./node_modules/@opensumi/ 3.62 MiB 607 modules
modules by path ./node_modules/lodash/*.js 80.7 KiB 117 modules
modules by path ./node_modules/jschardet/ 451 KiB 43 modules
modules by path ./node_modules/@furyjs/fury/ 167 KiB 35 modules
modules by path ./node_modules/fs-extra/ 54.8 KiB 34 modules
modules by path ./node_modules/iconv-lite/ 198 KiB 21 modules
modules by path ./node_modules/tar-stream/ 109 KiB 19 modules
modules by path ./node_modules/graceful-fs/*.js 25.4 KiB 4 modules
modules by path ./src/ 2.53 KiB 3 modules
modules by path ./node_modules/nanoid/ 1.43 KiB 2 modules
modules by path ./node_modules/vscode-languageserver-types/lib/umd/ 90 KiB 2 modules
modules by path ./node_modules/react/ 6.95 KiB 2 modules
modules by path ./node_modules/inherits/*.js 1000 bytes 2 modules
+ 51 modules

WARNING in ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/network.js 182:45-52
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/resources.js 9:18-38
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/async.js 12:20-42
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/glob.js 9:16-34
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/editor/common/languageSelector.js 8:15-48
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/editor/common/languageFeatureRegistry.js 11:27-56
 @ ./node_modules/@opensumi/ide-extension/lib/common/vscode/model.api.js 7:34-118
 @ ./node_modules/@opensumi/ide-extension/lib/common/vscode/converter.js 16:35-57
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/api/vscode/ext.host.comments.js 12:50-93
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/api/vscode/ext.host.api.impl.js 20:28-58
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/ext.host.js 13:28-69
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/ext.process-base.js 81:22-43
 @ ./src/extension/index.ts 3:30-95

WARNING in ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/network.js 223:45-52
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/resources.js 9:18-38
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/async.js 12:20-42
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/glob.js 9:16-34
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/editor/common/languageSelector.js 8:15-48
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/editor/common/languageFeatureRegistry.js 11:27-56
 @ ./node_modules/@opensumi/ide-extension/lib/common/vscode/model.api.js 7:34-118
 @ ./node_modules/@opensumi/ide-extension/lib/common/vscode/converter.js 16:35-57
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/api/vscode/ext.host.comments.js 12:50-93
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/api/vscode/ext.host.api.impl.js 20:28-58
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/ext.host.js 13:28-69
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/ext.process-base.js 81:22-43
 @ ./src/extension/index.ts 3:30-95

WARNING in ./node_modules/vscode-languageserver-types/lib/umd/main.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@opensumi/ide-extension/lib/common/vscode/converter.js 6:38-76
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/api/vscode/ext.host.comments.js 12:50-93
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/api/vscode/ext.host.api.impl.js 20:28-58
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/ext.host.js 13:28-69
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/ext.process-base.js 81:22-43
 @ ./src/extension/index.ts 3:30-95

3 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.87.0 compiled with 3 warnings in 101372 ms

asset index.worker.js 1.94 MiB [emitted] [minimized] [big] (name: main) 1 related asset
asset 132.index.worker.js 323 KiB [emitted] [minimized] [big] (id hint: vendors)
runtime modules 4.5 KiB 10 modules
orphan modules 110 bytes [orphan] 1 module
modules by path ./node_modules/@opensumi/ 3.03 MiB 517 modules
modules by path ./node_modules/lodash/*.js 80.7 KiB 117 modules
modules by path ./node_modules/jschardet/ 451 KiB 43 modules
modules by path ./node_modules/@furyjs/fury/ 167 KiB 35 modules
modules by path ./node_modules/iconv-lite/ 198 KiB 21 modules
modules by path ./node_modules/vscode-languageserver-types/lib/umd/ 90 KiB
  ./node_modules/vscode-languageserver-types/lib/umd/main.js 89.8 KiB [built] [code generated]
  ./node_modules/vscode-languageserver-types/lib/umd/ sync 160 bytes [built] [code generated]
modules by path ./node_modules/react/ 6.95 KiB
  ./node_modules/react/index.js 190 bytes [built] [code generated]
  ./node_modules/react/cjs/react.production.min.js 6.77 KiB [built] [code generated]
+ 19 modules

WARNING in ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/network.js 182:45-52
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/resources.js 9:18-38
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/async.js 12:20-42
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/glob.js 9:16-34
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/editor/common/languageSelector.js 8:15-48
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/editor/common/languageFeatureRegistry.js 11:27-56
 @ ./node_modules/@opensumi/ide-extension/lib/common/vscode/model.api.js 7:34-118
 @ ./node_modules/@opensumi/ide-extension/lib/common/vscode/converter.js 16:35-57
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/api/vscode/ext.host.command.js 7:50-93
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/api/worker/worker.host.api.impl.js 17:27-64
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/worker.host.js 14:31-75
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/worker.host-preload.js 7:22-46
 @ ./src/extension/index.worker.ts 3:0-65

WARNING in ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/network.js 223:45-52
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/resources.js 9:18-38
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/async.js 12:20-42
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/glob.js 9:16-34
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/editor/common/languageSelector.js 8:15-48
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/editor/common/languageFeatureRegistry.js 11:27-56
 @ ./node_modules/@opensumi/ide-extension/lib/common/vscode/model.api.js 7:34-118
 @ ./node_modules/@opensumi/ide-extension/lib/common/vscode/converter.js 16:35-57
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/api/vscode/ext.host.command.js 7:50-93
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/api/worker/worker.host.api.impl.js 17:27-64
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/worker.host.js 14:31-75
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/worker.host-preload.js 7:22-46
 @ ./src/extension/index.worker.ts 3:0-65

WARNING in ./node_modules/vscode-languageserver-types/lib/umd/main.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@opensumi/ide-extension/lib/common/vscode/converter.js 6:38-76
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/api/vscode/ext.host.command.js 7:50-93
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/api/worker/worker.host.api.impl.js 17:27-64
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/worker.host.js 14:31-75
 @ ./node_modules/@opensumi/ide-extension/lib/hosted/worker.host-preload.js 7:22-46
 @ ./src/extension/index.worker.ts 3:0-65

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  index.worker.js (1.94 MiB)
  132.index.worker.js (323 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (1.94 MiB)
      index.worker.js

3 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.87.0 compiled with 5 warnings in 95506 ms
assets by info 828 KiB [immutable]
  assets by path fonts/*.svg 341 KiB 62 assets
  assets by path fonts/*.ttf 233 KiB 4 assets
  + 3 assets
assets by path ../ 13 KiB 40 assets
assets by path *.js 11.3 MiB
  assets by chunk 501 KiB (id hint: vendors) 3 assets
  + 3 assets
assets by path *.ts 2.49 KiB
  asset project.d.ts 1.09 KiB [emitted]
  asset commands.d.ts 468 bytes [emitted]
  asset module.d.ts 391 bytes [emitted]
  + 3 assets
asset index.html 1.11 KiB [emitted]
Entrypoint main 11 MiB (643 KiB) = main.82f65af0.css 184 KiB bundle.js 10.8 MiB 68 auxiliary assets
4585 modules

WARNING in ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/network.js 182:45-52
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/editor/browser/services/openerService.js 23:18-57
 @ ./node_modules/@opensumi/ide-monaco/lib/browser/monaco.contribution.js 13:24-108
 @ ./node_modules/@opensumi/ide-monaco/lib/browser/index.js 9:30-62
 @ ./src/browser/index.ts 18:18-61

WARNING in ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/network.js 223:45-52
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/editor/browser/services/openerService.js 23:18-57
 @ ./node_modules/@opensumi/ide-monaco/lib/browser/monaco.contribution.js 13:24-108
 @ ./node_modules/@opensumi/ide-monaco/lib/browser/index.js 9:30-62
 @ ./src/browser/index.ts 18:18-61

WARNING in ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/performance.js 81:88-95
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/platform/storage/common/storage.js 11:22-65
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/editor/standalone/browser/standaloneServices.js 95:18-69
 @ ./node_modules/@opensumi/ide-monaco/lib/browser/monaco.context-key.service.js 10:29-120
 @ ./node_modules/@opensumi/ide-monaco/lib/browser/index.js 8:37-76
 @ ./src/browser/index.ts 18:18-61

WARNING in ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/performance.js 81:116-123
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/platform/storage/common/storage.js 11:22-65
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/editor/standalone/browser/standaloneServices.js 95:18-69
 @ ./node_modules/@opensumi/ide-monaco/lib/browser/monaco.context-key.service.js 10:29-120
 @ ./node_modules/@opensumi/ide-monaco/lib/browser/index.js 8:37-76
 @ ./src/browser/index.ts 18:18-61

WARNING in ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/performance.js 81:139-146
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/platform/storage/common/storage.js 11:22-65
 @ ./node_modules/@opensumi/monaco-editor-core/esm/vs/editor/standalone/browser/standaloneServices.js 95:18-69
 @ ./node_modules/@opensumi/ide-monaco/lib/browser/monaco.context-key.service.js 10:29-120
 @ ./node_modules/@opensumi/ide-monaco/lib/browser/index.js 8:37-76
 @ ./src/browser/index.ts 18:18-61

5 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.87.0 compiled with 5 warnings in 204616 ms
  • electron-builder  version=23.6.0 os=10.0.19045
  • author is missed in the package.json  appPackageFile=D:\code\opensumi\ide-electron\app\package.json
  • writing effective config  file=out\builder-effective-config.yaml
  • installing production dependencies  platform=win32 arch=x64 appDir=D:\code\opensumi\ide-electron\app
(node:12392) UnhandledPromiseRejectionWarning: Error: C:\Program Files\nodejs\node.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
Output:
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Error output:
warning @opensumi/vscode-ripgrep@1.4.0: Please use @opensumi/ripgrep instead
warning spdlog@0.11.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
error D:\code\opensumi\ide-electron\app\node_modules\spdlog: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: D:\code\opensumi\ide-electron\app\node_modules\spdlog
Output:
D:\code\opensumi\ide-electron\app\node_modules\spdlog>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.1
gyp info using node@14.21.3 | win32 | x64
gyp info find Python using Python version 3.12.4 found at "C:\Python312\python.exe"
gyp info find VS using VS2017 (15.9.35027.97) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python312\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\code\\opensumi\\ide-electron\\app\\node_modules\\spdlog\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\.electron-gyp\\22.3.25\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\.electron-gyp\\22.3.25',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Administrator\\\\.electron-gyp\\\\22.3.25\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\code\\opensumi\\ide-electron\\app\\node_modules\\spdlog',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\code\\opensumi\\ide-electron\\app\\node_modules\\spdlog\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  main.cc
  logger.cc
  win_delay_load_hook.cc
c:\users\administrator\.electron-gyp\22.3.25\include\node\node.h(27): fatal error C1189: #error:  "It looks like you are building this native module without using the right config.gypi.  This normally means that you need to update electron-rebuild (>=3.2.8) or node-gyp (>=9.0.0) if you're building modules directly." (编译源文件 ..\src\logger.cc) [D:\code\opensumi\ide-electron\app\node_modules\spdlog\build\spdlog.vcxproj]
c:\users\administrator\.electron-gyp\22.3.25\include\node\node.h(27): fatal error C1189: #error:  "It looks like you are building this native module without using the right config.gypi.  This normally means that you need to update electron-rebuild (>=3.2.8) or node-gyp (>=9.0.0) if you're building modules directly." (编译源文件 ..\src\main.cc) [D:\code\opensumi\ide-electron\app\node_modules\spdlog\build\spdlog.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\code\opensumi\ide-electron\app\node_modules\spdlog
gyp ERR! node -v v14.21.3
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok

    at ChildProcess.<anonymous> (D:\code\opensumi\ide-electron\node_modules\builder-util\src\util.ts:250:14)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.cp.emit (D:\code\opensumi\ide-electron\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1088:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12392) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12392) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 255.18s.

**Comment by john-deng** [comment]
@alex-jh-jiang I got the same issue and fixed it, will submit the PR soon.

**Comment by bytemain** [comment]
closed in #112
