### ISSUE TITLE
linux 桌面版的支持

### ISSUE THREAD

**Issue by ViokingTung** [opensumi/ide-electron#2]
electron开发的，可以给Linux的发行版打个包吗

**Comment by yantze** [comment]
> electron开发的，可以给Linux的发行版打个包吗

可以的，今天发一个新版本

**Comment by luoei** [comment]
有了吗

**Comment by yantze** [comment]
已支持
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/2226423/177452183-06c1b1dc-217d-4cfe-b147-177cb25ad07a.png">

https://github.com/opensumi/ide-electron/releases/tag/v1.3.6

**Comment by yantze** [comment]
如果没有其它问题，就先关了
