### ISSUE TITLE
开发环境启动失败，提示[node]innerError Error: Cannot find module '../build/Debug/pty.node'

### ISSUE THREAD

**Issue by tyn1998** [opensumi/ide-electron#23]
本地环境：
- macOS Monterey ARM
- node v18.2.0 & v14.17.6
- npm & yarn

事情起因是pull了最新的代码并且重新npm install了下，发现npm run start出问题了。然后折腾了很久，折腾内容包括：
- 删除node_modules，按照最新的README用yarn install
- 使用2个node版本、使用npm和yarn（一共四种组合）
- checkout五月份的几个commit测试（这点最让人困惑，重返到之前版本并重新安装依赖为什么也不行）
- 重新clone了一次仓库并按照步骤来

结果是都不正常。其中，使用 最新代码 + yarn + node v14.17.6 得到的terminal提示为：
<img width="1505" alt="image" src="https://user-images.githubusercontent.com/32434520/174472109-94c4a407-cd1c-43d1-a511-82f8798d7ac4.png">

Electron能启动，dock栏中有图标，但是窗口只有一片灰黑，没有任何内容，也不能拖动窗口：
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/32434520/174472125-d9fa8d25-bf12-40cf-9666-1ef32af90633.png">

**Comment by tyn1998** [comment]
eee，破案了！我没有运行“Startup”中的命令 😭 

<img width="889" alt="image" src="https://user-images.githubusercontent.com/32434520/174472798-303bf147-5bbb-43b6-9ede-15c12dbc12cd.png">

**Comment by yantze** [comment]
一般提示 pty.node 没有，导致画面空白，都是没有编译原生依赖。 一般执行一下 yarn run rebuild-native 就好。
