### ISSUE TITLE
Tauri支持

### ISSUE THREAD

**Issue by tianlinzx** [opensumi/ide-electron#25]
Tauri发布1.0版本了，号称多个性能指标强于Electron，为什么不尝试支持Tauri ？

**Comment by yantze** [comment]
有往这方面改造的计划，OpenSumi 本身是前后端分离的。不过当前的 OpenSumi 有部份逻辑是需要 electron 的环境，之后会慢慢独立出来。

1. electron main 进程的逻辑
2. electron renderer 进程部分耦合了 Node.js 相关的依赖
