### ISSUE TITLE
Toggle left and right sidebar not working

### ISSUE THREAD

**Issue by nguyenhongphat0** [opensumi/ide-electron#36]
I used this template to init the project, and toggling the sidebars either using UI or 
```ts
const layoutService = useInjectable<IMainLayoutService>(IMainLayoutService);
layoutService.toggleSlot(SlotLocation.right, false);
```
didn't work. Please view the recorded below 👇 

https://user-images.githubusercontent.com/29925961/179694564-48bb6c35-7fcd-4006-86fc-c071986ccb4a.mov

Thank you for support 🙏

**Comment by erha19** [comment]
@nguyenhongphat0 Hi, I create a sample here [opensumi-module-samples#7](https://github.com/opensumi/opensumi-module-samples/pull/7) , you can see the `Toggle Panel or Sidebar` demo know-how to use it.

**Comment by erha19** [comment]
And the Electron client can not get `IMainLayoutService` service instance directly, maybe you should use a custom `EventService` to make it work.
