### ISSUE TITLE
yarn build报错

### ISSUE THREAD

**Issue by fjb040911** [opensumi/ide-electron#38]
全新clone下来的代码。 
nodejs v14.2.9
在Windows和Mac上都尝试了，均报如下错误
`ERROR in /Users/fangjianbing/work/yix/ide-electron/src/browser/index.ts(69,3)
      TS2322: Type 'typeof MainLayoutModule' is not assignable to type 'ConstructorOf<BrowserModule<any>, any[]>'.
  Construct signature return types 'MainLayoutModule' and 'BrowserModule<any>' are incompatible.
    The types of 'providers' are incompatible between these types.
      Type 'import("/Users/fangjianbing/work/yix/ide-electron/node_modules/@opensumi/di/dist/declare").Provider[]' is not assignable to type 'import("/Users/fangjianbing/work/yix/ide-electron/node_modules/@opensumi/ide-core-common/node_modules/@opensumi/di/dist/declare").Provider[]'....`

<img width="990" alt="Snipaste_2022-07-21_21-02-30" src="https://user-images.githubusercontent.com/8717555/180220045-5bd7877c-466a-4fa9-bd2f-1b3da36f03fc.png">

**Comment by yantze** [comment]
看起来是 @opensumi/di 版本不一致导致的， 最近更新的小版本应该要和 opensumi 框架要一致才行，晚点我提交更新一下

**Comment by yantze** [comment]
已修复，拉一下最新的 main 分支
