### ISSUE TITLE
linux 版本打开文件夹无法正常显示

### ISSUE THREAD

**Issue by wuzhaohui100** [opensumi/ide-electron#39]
OS：麒麟 V10 SP1 2203
下载：https://github.com/opensumi/ide-electron/releases/download/v1.3.6/Sumi-OSS-1.3.6.deb

文件-打开文件夹或打开工作区，无法正常显示

**Comment by erha19** [comment]
@wuzhaohui100 请提供一下具体的界面或录屏文件，同时查看一下开发者控制台是否有相关报错信息，有的话也提供一下

**Comment by wuzhaohui100** [comment]
> @wuzhaohui100 请提供一下具体的界面或录屏文件，同时查看一下开发者控制台是否有相关报错信息，有的话也提供一下

重启了一下系统，现在可以打开了
