### ISSUE TITLE
Error on win10

### ISSUE THREAD

**Issue by jacksontwu** [opensumi/ide-electron#4]
启动后无任何反应。
- windows10
- [OpenSumi-Desktop-1.3.1.exe](https://github.com/opensumi/ide-electron/releases/download/v1.0.3/OpenSumi-Desktop-1.3.1.exe)

![image](https://user-images.githubusercontent.com/59786894/156488408-2cdedfec-626e-4c34-a0e8-5f7520fc41de.png)

**Comment by yantze** [comment]
看起来是原生组件编译有问题，我们晚点发布一个新的版本

**Comment by yantze** [comment]
WIndows 版本已修复： https://github.com/opensumi/ide-electron/releases/tag/v1.3.2

**Comment by jacksontwu** [comment]
似乎还有这个报错，能否帮忙看看。
![image](https://user-images.githubusercontent.com/59786894/156907114-196df8d4-3cda-47ce-beae-bdedb92ac462.png)

**Comment by jacksontwu** [comment]
似乎还有这个报错，能否帮忙看看。
![image](https://user-images.githubusercontent.com/59786894/156907158-76bd2f51-9f7d-41a0-a5cb-4277c32d42dc.png)

**Comment by yantze** [comment]
> 似乎还有这个报错，能否帮忙看看。 ![image](https://user-images.githubusercontent.com/59786894/156907158-76bd2f51-9f7d-41a0-a5cb-4277c32d42dc.png)

感谢反馈，应该是 node-pty 的版本问题，我升级一下

**Comment by yantze** [comment]
已经修复到 1.3.3 的版本哦
https://github.com/opensumi/ide-electron/releases/tag/v1.3.3

**Comment by jacksontwu** [comment]
1.3.3版本安装后，点击图标无反应，未打开ui界面，帮忙看看哈

**Comment by yantze** [comment]
<img width="665" alt="image" src="https://user-images.githubusercontent.com/2226423/156955364-32015236-9d81-43ff-ae2e-11a264f6b4d0.png">
任务管理器里面是否还残留 OpenSumi 的进程，展开进程看看具体的信息

**Comment by jacksontwu** [comment]
> <img alt="image" width="664" src="https://user-images.githubusercontent.com/2226423/156955472-86074aa9-f0bd-442c-b5d1-6e8aa1e9123d.png">
> 
> 任务管理器里面是否还残留 OpenSumi 的进程，展开进程看看具体的信息

操作前后都没有OpenSumi进程。

**Comment by yantze** [comment]
试试通过 cmd 启动 OpenSumi ，看看有什么日志信息：
1. 打开 cmd 穿酷狗
2. 输入 `set KTLOG_SHOW_DEBUG=true`
3. 拖动 OpenSumi 的快捷方式到 cmd 窗口
4. 运行后会有一些日志信息
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/2226423/156958302-a3e6385c-167e-473d-a8ff-f756e0f1fdc5.png">
拷贝或者截图看看这些错误信息

**Comment by yantze** [comment]
> ![image](https://user-images.githubusercontent.com/59786894/156959219-6c3b9e16-56fe-43a5-beba-2aab915a48c5.png)

有点像是 Electron 版本不同导致的，可以截图更全一点吗。另外这种情况很有可能通过卸载可以解决。

**Comment by jacksontwu** [comment]
> 

只有这些报错，可能是我之前安装过其他版本，我去删除一下看看

**Comment by jacksontwu** [comment]
> > ![image](https://user-images.githubusercontent.com/59786894/156959219-6c3b9e16-56fe-43a5-beba-2aab915a48c5.png)
> 
> 有点像是 Electron 版本不同导致的，可以截图更全一点吗。另外这种情况很有可能通过卸载可以解决。

只有这些报错，可能是我之前安装过其他版本，我去删除一下看看

**Comment by jacksontwu** [comment]
1.3.3版本ok
