### ISSUE TITLE
yarn build 错误

### ISSUE THREAD

**Issue by dingdinglz** [opensumi/ide-electron#42]
Windows环境，yarn正常，yarn build 提示ERROR: Task not found: "'build:*'"

`PS D:\ide-electron> yarn build
yarn run v1.22.18
$ rimraf -rf ./app && rimraf -rf ./out && run-p 'build:*'
ERROR: Task not found: "'build:*'"
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by yantze** [comment]
先删除 'build:*' 两边的单引号，就能正常编译了。

> 这个是 run-p 在不同系统下不一致问题导致的，修复中

**Comment by dingdinglz** [comment]
> 先删除 'build:*' 两边的单引号，就能正常编译了。
> 
> > 这个是 run-p 在不同系统下不一致问题导致的，修复中

正常了
