### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by 767746649zyy** [opensumi/ide-electron#47]
E:\code\et_upper4>pnpm run pack:x64

> ETest@4.0.0 pack:x64 E:\code\et_upper4
> pnpm build && cross-env TARGET_ARCHES=x64 node build/pack.js

> ETest@4.0.0 build E:\code\et_upper4
> rimraf -rf ./app && rimraf -rf ./out && run-p build:browser build:node build:extension build:main build:webview

> ETest@4.0.0 build:browser E:\code\et_upper4
> webpack --config ./build/webpack.browser.config.js

> ETest@4.0.0 build:node E:\code\et_upper4
> webpack --config ./build/webpack.node.config.js

> ETest@4.0.0 build:extension E:\code\et_upper4
> webpack --config ./build/webpack.extension-host.config.js

> ETest@4.0.0 build:main E:\code\et_upper4
> webpack --config ./build/webpack.main.config.js

> ETest@4.0.0 build:webview E:\code\et_upper4
> webpack --config ./build/webpack.webview.config.js 

asset host-preload.js 21.9 KiB [emitted] (name: main) 1 related asset
asset plain-preload.js 1.35 KiB [emitted] [from: node_modules/.pnpm/@opensumi+ide-webview@2.18.15_cerooqu47yvd46iplnavuuclvu/node_modules/@opensumi/ide-webview/lib/electron-webview/plain-preload.js] [copied]
modules by path ./node_modules/.pnpm/@opensumi+ide-webview@2.18.15_cerooqu47yvd46iplnavuuclvu/node_modules/@opensumi/ide-webview/lib/electron-webview/*.js 2.12 KiB
  ./node_modules/.pnpm/@opensumi+ide-webview@2.18.15_cerooqu47yvd46iplnavuuclvu/node_modules/@opensumi/ide-webview/lib/electron-webview/host-preload.js 54 bytes [built] [code generated]
  ./node_modules/.pnpm/@opensumi+ide-webview@2.18.15_cerooqu47yvd46iplnavuuclvu/node_modules/@opensumi/ide-webview/lib/electron-webview/host-channel.js 2.07 KiB [built] [code generated]
modules by path ./node_modules/.pnpm/@opensumi+ide-webview@2.18.15_cerooqu47yvd46iplnavuuclvu/node_modules/@opensumi/ide-webview/lib/webview-host/*.js 15.3 KiB
  ./node_modules/.pnpm/@opensumi+ide-webview@2.18.15_cerooqu47yvd46iplnavuuclvu/node_modules/@opensumi/ide-webview/lib/webview-host/webview-manager.js 12.6 KiB [built] [code generated]
  ./node_modules/.pnpm/@opensumi+ide-webview@2.18.15_cerooqu47yvd46iplnavuuclvu/node_modules/@opensumi/ide-webview/lib/webview-host/common.js 2.62 KiB [built] [code generated]
external "electron" 42 bytes [built] [code generated]
webpack 5.74.0 compiled successfully in 231 ms
asset index.js 2.61 MiB [emitted] (name: main) 1 related asset
runtime modules 793 bytes 4 modules
modules by path ./node_modules/.pnpm/ 2.18 MiB
  javascript modules 2.1 MiB 400 modules
  json modules 86.7 KiB
    ./node_modules/.pnpm/iconv-lite@0.6.3/node_modules/iconv-lite/encodings/tables/shiftjis.json 8.78 KiB [built] [code generated]
    + 7 modules
modules by path ./src/ 19.2 KiB
  modules by path ./src/main/ 14.8 KiB
    modules by path ./src/main/*.ts 8.62 KiB 3 modules
    modules by path ./src/main/services/*.ts 6.15 KiB 2 modules
  modules by path ./src/common/ 4.47 KiB
    ./src/common/types.ts 2.59 KiB [built] [code generated]
    + 2 modules
+ 17 modules

WARNING in ./node_modules/.pnpm/yargs@17.5.1/node_modules/yargs/build/index.cjs 1:60106-60113
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/.pnpm/yargs@17.5.1/node_modules/yargs/index.cjs 5:29-57
 @ ./node_modules/.pnpm/@opensumi+ide-core-electron-main@2.18.15_electron@18.3.4/node_modules/@opensumi/ide-core-electron-main/lib/bootstrap/app.js 5:16-32
 @ ./node_modules/.pnpm/@opensumi+ide-core-electron-main@2.18.15_electron@18.3.4/node_modules/@opensumi/ide-core-electron-main/lib/bootstrap/index.js 4:21-37
 @ ./node_modules/.pnpm/@opensumi+ide-core-electron-main@2.18.15_electron@18.3.4/node_modules/@opensumi/ide-core-electron-main/lib/index.js 5:21-43
 @ ./src/main/launch.ts 9:33-76
 @ ./src/main/index.ts 6:17-36

WARNING in ./node_modules/.pnpm/yargs@17.5.1/node_modules/yargs/build/index.cjs 1:60498-60505
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/.pnpm/yargs@17.5.1/node_modules/yargs/index.cjs 5:29-57
 @ ./node_modules/.pnpm/@opensumi+ide-core-electron-main@2.18.15_electron@18.3.4/node_modules/@opensumi/ide-core-electron-main/lib/bootstrap/app.js 5:16-32
 @ ./node_modules/.pnpm/@opensumi+ide-core-electron-main@2.18.15_electron@18.3.4/node_modules/@opensumi/ide-core-electron-main/lib/bootstrap/index.js 4:21-37
 @ ./node_modules/.pnpm/@opensumi+ide-core-electron-main@2.18.15_electron@18.3.4/node_modules/@opensumi/ide-core-electron-main/lib/index.js 5:21-43
 @ ./src/main/launch.ts 9:33-76
 @ ./src/main/index.ts 6:17-36

WARNING in ./node_modules/.pnpm/yargs@17.5.1/node_modules/yargs/index.cjs 12:39-46
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/.pnpm/@opensumi+ide-core-electron-main@2.18.15_electron@18.3.4/node_modules/@opensumi/ide-core-electron-main/lib/bootstrap/app.js 5:16-32
 @ ./node_modules/.pnpm/@opensumi+ide-core-electron-main@2.18.15_electron@18.3.4/node_modules/@opensumi/ide-core-electron-main/lib/bootstrap/index.js 4:21-37
 @ ./node_modules/.pnpm/@opensumi+ide-core-electron-main@2.18.15_electron@18.3.4/node_modules/@opensumi/ide-core-electron-main/lib/index.js 5:21-43
 @ ./src/main/launch.ts 9:33-76
 @ ./src/main/index.ts 6:17-36

3 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.74.0 compiled with 3 warnings in 3448 ms
asset index.js 7.11 MiB [emitted] (name: main) 1 related asset
runtime modules 793 bytes 4 modules
javascript modules 5.28 MiB
  modules by path ./node_modules/.pnpm/ 5.26 MiB
    cacheable modules 5.26 MiB 1104 modules
    + 5 modules
  modules by path ./src/ 11.2 KiB 6 modules
  + 30 modules
json modules 932 KiB
  modules by path ./node_modules/.pnpm/har-schema@2.0.0/node_modules/har-schema/lib/ 6.93 KiB 18 modules
  modules by path ./node_modules/.pnpm/iconv-lite@0.6.3/node_modules/iconv-lite/ 86.7 KiB 8 modules
  modules by path ./node_modules/.pnpm/ajv@6.12.6/node_modules/ajv/lib/ 5.58 KiB
    ./node_modules/.pnpm/ajv@6.12.6/node_modules/ajv/lib/refs/json-schema-draft-06.json 2.46 KiB [built] [code generated]
    + 2 modules
  + 7 modules

WARNING in ./node_modules/.pnpm/@opensumi+ide-extension@2.18.15_k5fmzrynqzr2hjcg6enjf76gka/node_modules/@opensumi/ide-extension/lib/node/languagePack.js 292:25-32
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/.pnpm/@opensumi+ide-extension@2.18.15_k5fmzrynqzr2hjcg6enjf76gka/node_modules/@opensumi/ide-extension/lib/node/extension.service.client.js 13:32-57
 @ ./node_modules/.pnpm/@opensumi+ide-extension@2.18.15_k5fmzrynqzr2hjcg6enjf76gka/node_modules/@opensumi/ide-extension/lib/node/index.js 11:35-72
 @ ./src/node/index.ts 12:15-58

WARNING in ./node_modules/.pnpm/vscode-languageserver-types@3.17.2/node_modules/vscode-languageserver-types/lib/umd/main.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/.pnpm/@opensumi+ide-file-service@2.18.15_22kvxa7zeyivx4jp72v2w3pkvy/node_modules/@opensumi/ide-file-service/lib/node/file-service.js 10:38-76
 @ ./node_modules/.pnpm/@opensumi+ide-file-service@2.18.15_22kvxa7zeyivx4jp72v2w3pkvy/node_modules/@opensumi/ide-file-service/lib/node/index.js 9:23-48 10:21-46
 @ ./src/node/index.ts 6:15-61

WARNING in ./node_modules/.pnpm/yargs@17.5.1/node_modules/yargs/build/index.cjs 1:60106-60113
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/.pnpm/yargs@17.5.1/node_modules/yargs/index.cjs 5:29-57
 @ ./src/node/server.ts 6:35-51
 @ ./src/node/index.ts 4:17-36

WARNING in ./node_modules/.pnpm/yargs@17.5.1/node_modules/yargs/build/index.cjs 1:60498-60505
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/.pnpm/yargs@17.5.1/node_modules/yargs/index.cjs 5:29-57
 @ ./src/node/server.ts 6:35-51
 @ ./src/node/index.ts 4:17-36

WARNING in ./node_modules/.pnpm/yargs@17.5.1/node_modules/yargs/index.cjs 12:39-46
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./src/node/server.ts 6:35-51
 @ ./src/node/index.ts 4:17-36

5 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.74.0 compiled with 5 warnings in 5460 ms
asset index.js 5.51 MiB [emitted] (name: main) 1 related asset
runtime modules 793 bytes 4 modules
cacheable modules 4.65 MiB
  javascript modules 4.53 MiB
    modules by path ./node_modules/.pnpm/ 4.53 MiB 849 modules
    modules by path ./src/ 2.53 KiB
      ./src/extension/index.ts 665 bytes [built] [code generated]
      ./src/common/constants.ts 767 bytes [built] [code generated]
      ./src/common/node/utils.ts 1.13 KiB [built] [code generated]
  json modules 121 KiB
    modules by path ./node_modules/.pnpm/iconv-lite@0.6.3/node_modules/iconv-lite/ 86.7 KiB 8 modules
    ./node_modules/.pnpm/@opensumi+ide-core-common@2.18.15/node_modules/@opensumi/ide-core-common/lib/hash-calculate/md5.wasm.json 4.04 KiB [built] [code generated]
    ./node_modules/.pnpm/statuses@1.5.0/node_modules/statuses/codes.json 1.54 KiB [built] [code generated]
    ./node_modules/.pnpm/@opensumi+monaco-editor-core@0.29.1-patch.1/node_modules/@opensumi/monaco-editor-core/dev/vs/editor/editor.main.nls.zh-cn.json 28.7 KiB [built] [code generated]
+ 26 modules

WARNING in ./node_modules/.pnpm/vscode-languageserver-types@3.17.2/node_modules/vscode-languageserver-types/lib/umd/main.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/.pnpm/@opensumi+ide-extension@2.18.15_k5fmzrynqzr2hjcg6enjf76gka/node_modules/@opensumi/ide-extension/lib/common/vscode/converter.js 7:38-76
 @ ./node_modules/.pnpm/@opensumi+ide-extension@2.18.15_k5fmzrynqzr2hjcg6enjf76gka/node_modules/@opensumi/ide-extension/lib/hosted/api/vscode/ext.host.command.js 7:50-93
 @ ./node_modules/.pnpm/@opensumi+ide-extension@2.18.15_k5fmzrynqzr2hjcg6enjf76gka/node_modules/@opensumi/ide-extension/lib/hosted/api/vscode/ext.host.api.impl.js 16:27-56
 @ ./node_modules/.pnpm/@opensumi+ide-extension@2.18.15_k5fmzrynqzr2hjcg6enjf76gka/node_modules/@opensumi/ide-extension/lib/hosted/ext.host.js 13:28-69
 @ ./node_modules/.pnpm/@opensumi+ide-extension@2.18.15_k5fmzrynqzr2hjcg6enjf76gka/node_modules/@opensumi/ide-extension/lib/hosted/ext.process-base.js 72:22-43
 @ ./src/extension/index.ts 3:30-95

WARNING in ./node_modules/.pnpm/yargs@17.5.1/node_modules/yargs/build/index.cjs 1:60106-60113
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/.pnpm/yargs@17.5.1/node_modules/yargs/index.cjs 5:29-57
 @ ./node_modules/.pnpm/@opensumi+ide-extension@2.18.15_k5fmzrynqzr2hjcg6enjf76gka/node_modules/@opensumi/ide-extension/lib/hosted/ext.process-base.js 20:13-34
 @ ./src/extension/index.ts 3:30-95

WARNING in ./node_modules/.pnpm/yargs@17.5.1/node_modules/yargs/build/index.cjs 1:60498-60505
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/.pnpm/yargs@17.5.1/node_modules/yargs/index.cjs 5:29-57
 @ ./node_modules/.pnpm/@opensumi+ide-extension@2.18.15_k5fmzrynqzr2hjcg6enjf76gka/node_modules/@opensumi/ide-extension/lib/hosted/ext.process-base.js 20:13-34
 @ ./src/extension/index.ts 3:30-95

WARNING in ./node_modules/.pnpm/yargs@17.5.1/node_modules/yargs/index.cjs 12:39-46
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/.pnpm/@opensumi+ide-extension@2.18.15_k5fmzrynqzr2hjcg6enjf76gka/node_modules/@opensumi/ide-extension/lib/hosted/ext.process-base.js 20:13-34
 @ ./src/extension/index.ts 3:30-95

4 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.74.0 compiled with 4 warnings in 6252 ms

asset index.worker.js 4.03 MiB [emitted] (name: main) 1 related asset
runtime modules 1010 bytes 5 modules
modules by path ./node_modules/.pnpm/ 3.35 MiB
  javascript modules 3.24 MiB 610 modules
  json modules 115 KiB
    ./node_modules/.pnpm/iconv-lite@0.6.3/node_modules/iconv-lite/encodings/tables/shiftjis.json 8.78 KiB [built] [code generated]
    ./node_modules/.pnpm/iconv-lite@0.6.3/node_modules/iconv-lite/encodings/tables/eucjp.json 15.1 KiB [built] [code generated]
    ./node_modules/.pnpm/iconv-lite@0.6.3/node_modules/iconv-lite/encodings/tables/cp936.json 20.1 KiB [built] [code generated]
    + 6 modules
+ 12 modules

WARNING in ./node_modules/.pnpm/vscode-languageserver-types@3.17.2/node_modules/vscode-languageserver-types/lib/umd/main.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/.pnpm/@opensumi+ide-extension@2.18.15_k5fmzrynqzr2hjcg6enjf76gka/node_modules/@opensumi/ide-extension/lib/common/vscode/converter.js 7:38-76
 @ ./node_modules/.pnpm/@opensumi+ide-extension@2.18.15_k5fmzrynqzr2hjcg6enjf76gka/node_modules/@opensumi/ide-extension/lib/hosted/api/vscode/ext.host.command.js 7:50-93
 @ ./node_modules/.pnpm/@opensumi+ide-extension@2.18.15_k5fmzrynqzr2hjcg6enjf76gka/node_modules/@opensumi/ide-extension/lib/hosted/api/worker/worker.host.api.impl.js 15:27-64
 @ ./node_modules/.pnpm/@opensumi+ide-extension@2.18.15_k5fmzrynqzr2hjcg6enjf76gka/node_modules/@opensumi/ide-extension/lib/hosted/worker.host.js 12:31-75
 @ ./node_modules/.pnpm/@opensumi+ide-extension@2.18.15_k5fmzrynqzr2hjcg6enjf76gka/node_modules/@opensumi/ide-extension/lib/hosted/worker.host-preload.js 8:22-46
 @ ./src/extension/index.worker.ts 3:0-65

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.74.0 compiled with 1 warning in 5717 ms
assets by path ../ 116 KiB 176 assets
assets by info 797 KiB [immutable] 68 assets
assets by path components/ 5.3 KiB
  assets by path components/PropertySettingPanel/*.ts 1.41 KiB 4 assets
  assets by path components/CaseTreePannel/*.ts 1.11 KiB 2 assets
  + 8 assets
assets by path *.ts 2.49 KiB
  asset project.d.ts 1.09 KiB [emitted]
  asset commands.d.ts 468 bytes [emitted]
  + 4 assets
assets by path *.js 26.6 MiB
  asset bundle.js 26.6 MiB [emitted] (name: main) 1 related asset
  asset preload.js 1.73 KiB [emitted] [from: node_modules/.pnpm/@opensumi+ide-core-electron-main@2.18.15_electron@18.3.4/node_modules/@opensumi/ide-core-electron-main/browser-preload/index.js] [copied]
asset index.html 1.18 KiB [emitted]
Entrypoint main 26.8 MiB (28.1 MiB) = main.75ee9e84.css 199 KiB bundle.js 26.6 MiB 69 auxiliary assets
runtime modules 70.2 KiB 311 modules
orphan modules 440 KiB (javascript) 66.3 KiB (asset) [orphan] 90 modules
modules by path ./node_modules/.pnpm/ 21.2 MiB (javascript) 545 KiB (asset) 119 KiB (css/mini-extract)
  javascript modules 21.1 MiB 3036 modules
  asset modules 2.87 KiB (javascript) 545 KiB (asset) 70 modules
  css modules 119 KiB 70 modules
  json modules 134 KiB 21 modules
modules by path ./src/ 1.16 MiB (javascript) 23.2 KiB (css/mini-extract)
  modules by path ./src/modules/ 1.03 MiB (javascript) 171 bytes (css/mini-extract) 223 modules
  modules by path ./src/browser/ 132 KiB (javascript) 23 KiB (css/mini-extract) 44 modules
  modules by path ./src/common/ 4.84 KiB
    modules by path ./src/common/i18n/*.ts 1.5 KiB 3 modules
    modules by path ./src/common/*.ts 3.33 KiB 2 modules
  ./src/extensionManager/browser.ts 345 bytes [built] [code generated]
+ 12 modules
webpack 5.74.0 compiled successfully in 26696 ms
  • electron-builder  version=23.3.3 os=10.0.19044
  • author is missed in the package.json  appPackageFile=E:\code\et_upper4\app\package.json
  • writing effective config  file=out-x64\builder-effective-config.yaml
  • installing production dependencies  platform=win32 arch=x64 appDir=E:\code\et_upper4\app
(node:12480) UnhandledPromiseRejectionWarning: Error: C:\Program Files\nodejs\node.exe process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
Output:
Progress: resolved 1, reused 0, downloaded 0, added 0
 WARN  deprecated @opensumi/vscode-ripgrep@1.4.0: Please use @opensumi/ripgrep instead
Packages: +12
++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: E:\.pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm
.../node_modules/node-pty install$ node scripts/install.js
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install$ node-gyp rebuild
.../spdlog@0.11.1/node_modules/spdlog install$ node-gyp rebuild
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: E:\code\et_upper4\app\node_modules\.pnpm\nsfw@2.1.2\node_modules\nsfw>if not defined npm_config_node_gyp (node "C:\Users\KyDev02\AppData\Roaming\npm\node_modules\pnpm\dist\node-gyp-bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\KyDev02\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\bin\node-gyp.js" rebuild )
.../spdlog@0.11.1/node_modules/spdlog install: E:\code\et_upper4\app\node_modules\.pnpm\spdlog@0.11.1\node_modules\spdlog>if not defined npm_config_node_gyp (node "C:\Users\KyDev02\AppData\Roaming\npm\node_modules\pnpm\dist\node-gyp-bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\KyDev02\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\bin\node-gyp.js" rebuild )
.../node_modules/node-pty install: E:\code\et_upper4\app\node_modules\.pnpm\node-pty@0.10.0\node_modules\node-pty>if not defined npm_config_node_gyp (node "C:\Users\KyDev02\AppData\Roaming\npm\node_modules\pnpm\dist\node-gyp-bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\KyDev02\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\bin\node-gyp.js" rebuild )
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: gyp info it worked if it ends with ok
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: gyp info using node-gyp@9.1.0
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: gyp info using node@14.17.6 | win32 | x64
.../spdlog@0.11.1/node_modules/spdlog install: gyp info it worked if it ends with ok
.../spdlog@0.11.1/node_modules/spdlog install: gyp info using node-gyp@9.1.0
.../spdlog@0.11.1/node_modules/spdlog install: gyp info using node@14.17.6 | win32 | x64
.../node_modules/node-pty install: gyp info it worked if it ends with ok
.../node_modules/node-pty install: gyp info using node-gyp@9.1.0
.../node_modules/node-pty install: gyp info using node@14.17.6 | win32 | x64
.../spdlog@0.11.1/node_modules/spdlog install: gyp info find Python using Python version 3.7.9 found at "D:\Program Files (x86)\ETest3\python37\python.exe"
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: gyp info find Python using Python version 3.7.9 found at "D:\Program Files (x86)\ETest3\python37\python.exe"
.../node_modules/node-pty install: gyp info find Python using Python version 3.7.9 found at "D:\Program Files (x86)\ETest3\python37\python.exe"
Progress: resolved 12, reused 12, downloaded 0, added 12, done
.../spdlog@0.11.1/node_modules/spdlog install: gyp http GET https://electronjs.org/headers/v18.3.4/node-v18.3.4-headers.tar.gz
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: gyp http GET https://electronjs.org/headers/v18.3.4/node-v18.3.4-headers.tar.gz
.../node_modules/node-pty install: gyp http GET https://electronjs.org/headers/v18.3.4/node-v18.3.4-headers.tar.gz
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: gyp WARN install got an error, rolling back install
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: gyp ERR! configure error
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: gyp ERR! stack FetchError: request to https://www.electronjs.org/headers/v18.3.4/node-v18.3.4-headers.tar.gz failed, reason: read ECONNRESET
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: gyp ERR! stack     at ClientRequest.<anonymous> (C:\Users\KyDev02\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\minipass-fetch\lib\index.js:130:14)
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: gyp ERR! stack     at ClientRequest.emit (events.js:400:28)
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:475:9)
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: gyp ERR! stack     at TLSSocket.emit (events.js:412:35)
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:106:8)
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: gyp ERR! stack     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: gyp ERR! System Windows_NT 10.0.19044
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\KyDev02\\AppData\\Roaming\\npm\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: gyp ERR! cwd E:\code\et_upper4\app\node_modules\.pnpm\nsfw@2.1.2\node_modules\nsfw
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: gyp ERR! node -v v14.17.6
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: gyp ERR! node-gyp -v v9.1.0
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: gyp ERR! not ok
.../spdlog@0.11.1/node_modules/spdlog install: gyp WARN install got an error, rolling back install
.../spdlog@0.11.1/node_modules/spdlog install: gyp ERR! configure error
.../spdlog@0.11.1/node_modules/spdlog install: gyp ERR! stack FetchError: request to https://www.electronjs.org/headers/v18.3.4/node-v18.3.4-headers.tar.gz failed, reason: read ECONNRESET
.../spdlog@0.11.1/node_modules/spdlog install: gyp ERR! stack     at ClientRequest.<anonymous> (C:\Users\KyDev02\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\minipass-fetch\lib\index.js:130:14)
.../spdlog@0.11.1/node_modules/spdlog install: gyp ERR! stack     at ClientRequest.emit (events.js:400:28)
.../spdlog@0.11.1/node_modules/spdlog install: gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:475:9)
.../spdlog@0.11.1/node_modules/spdlog install: gyp ERR! stack     at TLSSocket.emit (events.js:412:35)
.../spdlog@0.11.1/node_modules/spdlog install: gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:106:8)
.../spdlog@0.11.1/node_modules/spdlog install: gyp ERR! stack     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
.../spdlog@0.11.1/node_modules/spdlog install: gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
.../spdlog@0.11.1/node_modules/spdlog install: gyp ERR! System Windows_NT 10.0.19044
.../spdlog@0.11.1/node_modules/spdlog install: gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\KyDev02\\AppData\\Roaming\\npm\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
.../spdlog@0.11.1/node_modules/spdlog install: gyp ERR! cwd E:\code\et_upper4\app\node_modules\.pnpm\spdlog@0.11.1\node_modules\spdlog
.../spdlog@0.11.1/node_modules/spdlog install: gyp ERR! node -v v14.17.6
.../spdlog@0.11.1/node_modules/spdlog install: gyp ERR! node-gyp -v v9.1.0
.../spdlog@0.11.1/node_modules/spdlog install: gyp ERR! not ok
.../.pnpm/nsfw@2.1.2/node_modules/nsfw install: Failed
 ELIFECYCLE  Command failed with exit code 1.

    at ChildProcess.<anonymous> (E:\code\et_upper4\node_modules\.pnpm\builder-util@23.3.3\node_modules\builder-util\src\util.ts:250:14)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.cp.emit (E:\code\et_upper4\node_modules\.pnpm\cross-spawn@7.0.3\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12480) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by 767746649zyy** [comment]
node v14.17.6

**Comment by bytemain** [comment]
这个看起来是网络错误：FetchError: request to [electronjs.org/headers/v18.3.4/node-v18.3.4-headers.tar.gz](https://www.electronjs.org/headers/v18.3.4/node-v18.3.4-headers.tar.gz) failed, reason: read ECONNRESET

切换到 main-cn 分支再重新打包吧，main-cn 这个分支有中国镜像的配置
