### ISSUE TITLE
Is there any minimum OS version requirement for Linux?

### ISSUE THREAD

**Issue by nguyenhongphat0** [opensumi/ide-electron#50]
Hi team, thank you for an amazing project!

I'm struggling with this issue for a long time, so I posted it here in case someone know what is wrong with it 👇 

On Ubuntu 20.x, the IDE show a blank screen without any log:

![z3843904723343_1afcf380d40c9057b991a5c6b9d18d22](https://user-images.githubusercontent.com/29925961/198990877-6e7ae0e8-8a60-41f5-aaa5-f777886493fe.jpg)

(the `no static exports` found - as what I researched - is just a warning and have title possibility of causing the blank issue, but if there is any advice for fixing it would be great)

On Ubuntu 22.x, it's working properly:

![z3843915398556_1e6ea41e498b2d10017cd089962b4138](https://user-images.githubusercontent.com/29925961/198991752-7d3a79b9-3c3a-4a67-9012-f24b9cecb9bb.jpg)

The annoying about the issue is there is no obvious error log so that I didn't know exactly what went wrong. Please let me know if there is anything I can do to make it work, any help is appreciated! 🙏

**Comment by erha19** [comment]
@nguyenhongphat0  I search the errors and found a blog [[Solving Google Chrome's gpu-process error message in Ubuntu Linux](https://simpleit.rocks/linux/ubuntu/fixing-common-google-chrome-gpu-process-error-message-in-linux/)](https://simpleit.rocks/linux/ubuntu/fixing-common-google-chrome-gpu-process-error-message-in-linux/)

Maybe you should disable the GPU process on Ubuntu 20.x with `--disable-gpu` flag.

**Comment by nguyenhongphat0** [comment]
`--disable-gpu` didn't work for me. However when applying the build (with the same process) on the older machine that was running Ubuntu 20.x, the build worked as supposed 🤔 
I'm still confuse why this happen. But we can close this issue for now 😅
