### ISSUE TITLE
还维护吗？版本落后VSCODE太多了

### ISSUE THREAD

**Issue by richwxd** [opensumi/ide-electron#52]
最后提交的代码都是3个月前了

**Comment by erha19** [comment]
@richwxd 该项目为 OpenSumi 在 Electron 上的集成示例，依赖 https://github.com/opensumi/core 内核，并非主体仓库，也非 VS Code 同类产品。

如对版本有需求，可以自行升级使用，本仓库内仅会修复必要的 bug，更新频率较低。

**Comment by hwhsu1231** [comment]
@erha19 - 如果可以的話，希望 [opensumi/electron](https://github.com/opensumi/ide-electron) 可以持續更新追上 [opensumi/core](https://github.com/opensumi/core) 最新的版本。因為前者比起後者更容易一鍵安裝使用，畢竟有已經打包好的安裝包可以直接使用。

**Comment by yantze** [comment]
@hwhsu1231 ide-electron 最新的提交包含的是 opensumi/core 2.21.10，比如最新的是 2.22.1，可以手动升级使用。

我们也会尽量保持大版本的升级跟随，这次是因为春节前夕发布了 2.22.x 的版本，所以没有跟上。

**Comment by yantze** [comment]
ide-electron main 分支已经升级到 2.22.1
