### ISSUE TITLE
中文路径下，编译时报错

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/ide-electron#65]
![image](https://user-images.githubusercontent.com/13432873/227411908-ca51069b-84ab-45cf-8ae2-17670f215b17.png)

**Comment by erha19** [comment]
@zhuzeyu22 许多原生库的编译都会受中文路径影响，应用开发别用中文命名文件夹吧。

**Comment by zhuzeyu22** [comment]
@erha19 windows 环境下是否可以跳过编译的步骤，npm 包应该都是平台无关的为啥还要编译？

**Comment by zhuzeyu22** [comment]
> @erha19 windows 环境下是否可以跳过编译的步骤，npm 包应该都是平台无关的为啥还要编译？

似乎影响到了一些全局的东西，修改到全英文路径后，依然报同样的错误

**Comment by erha19** [comment]
@zhuzeyu22 部分 npm 包，如  `node-pty`, `spdlog` 等是与平台强相关的，需要根据不同平台编译构建产物，如果遇到了相关问题，可以到网上检索一下相关问题解决方案或提供完整报错信息。

**Comment by zhuzeyu22** [comment]
@erha19 找到原因了。是 python 版本原因，昨天 安装了 3.11.x 的python 版本，版本回退之后，再次测试，中文路径下无异常。
