### ISSUE TITLE
如何调用我们开发的编译器？

### ISSUE THREAD

**Issue by justin2gh** [opensumi/ide-electron#67]
我们想集成我们开发的汇编编译器到opensumi，如何调用？我们的编译器已经编译成Windows平台的exe文件，已经可以通过命令行调用执行： C:\compiler.exe  C:\projectsFolder

**Comment by yantze** [comment]
都可以用插件的方式集成
1. 可以用 task 的方式，OpenSumi 的插件兼容 VSCode  https://code.visualstudio.com/Docs/editor/tasks
2. 使用 Terminal 的方式 https://code.visualstudio.com/api/references/vscode-api createTerminal 接口

**Comment by justin2gh** [comment]
我们不想用插件的方式，那会展示在插件列表里面，我们已经实现了在vscode上以插件的形式完成项目代码的编译，我们希望直接集成到opensumi

**Comment by justin2gh** [comment]
我们开发了我们自己的MCU，正在寻找IDE框架集成我们的编译器，我们希望完整的定制编译器的功能。正在尝试在opensumi上做相关探索，发现资料和案例很少，定制起来很困难。以下是第一阶段的需求：
# IDE Stage 1 OKR
## Objective: Successfully develop a customized desktop IDE software based on opensumi（Electron）, and promote it to the market.

## Key Result 1: Integrate the assembler compiler and successfully integrate it

- Integrate the assembler compiler into our IDE project and test its functionality and stability.
- Output the compilation result to the output panel
- Output compilation error information to the problem panel

## Key Result 2: Assemble project compilation by clicking icons or command panels

- Design and develop a user interface(build button) to launch the assembler compiler.
- Develop corresponding code to implement project compilation on the UI.
- Provide "Build" on the command palette to launch compilation.

## Key Result 3: Implement error locating function

- Locat Error line based on problems panel information output by the assembler.
- Develop UI-related code, so that users can double-click on the error line and automatically jump to the error code line.
- Automatically activate the code locating function to locate the error to the correct position in the code, saving users time and effort.
- Test and prove the effectiveness and accuracy of the error-locating function.

## Key Result 4: Package the IDE tool project into an exe installation file and provide it to customers for use

- Set up the process of packaging and publishing the IDE, ensuring the security and reliability of the publishing process.
- Publish the installation files according to the specified manner and schedule.
Provide reliable installation documents and support to help customers use the IDE smoothly.

## Key Result 5: UI interface conforms to the company's brand identification, including logo, about, etc.

- Confirm and understand the company's brand identification principles, such as color range, font, icons, etc.
- Revise the UI design according to the company's brand identification principles, including logo, buttons, panels, etc.
- Create an "about us" page and modify or update terms and policies based on the company's latest information.

**Comment by justin2gh** [comment]
by the way, 基于opensumi定制IDE，需要开发人员具备哪些技能？

**Comment by erha19** [comment]
@justin2gh 我们提供了一些拓展案例，可以看这里 https://github.com/opensumi/opensumi-module-samples#samples ，看你这里的基础逻辑，其实只需要把执行构建的逻辑封装为一个 Node 层方法即可，可以参考 `[Connection Sample](https://github.com/opensumi/opensumi-modue-samples/tree/main/modules/connection)` 这个案例。

> 基于opensumi定制IDE，需要开发人员具备哪些技能？

NodeJS/Typescript/React 开发能力，辅助性的如：VS Code 插件开发经验，依赖注入知识

**Comment by justin2gh** [comment]
@erha19 非常感谢，后续开发过程中又问题在来提问。

**Comment by justin2gh** [comment]
@erha19 非常感谢，后续开发过程中有问题再来提问。
