### ISSUE TITLE
WIN 7平台安装依赖异常

### ISSUE THREAD

**Issue by zt6991** [opensumi/ide-electron#71]
以下是安装依赖报错

$ pnpm i
Lockfile is up-to-date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +1065
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1065, reused 0, downloaded 0, added 0
Progress: resolved 1065, reused 55, downloaded 0, added 0
Progress: resolved 1065, reused 97, downloaded 0, added 0
Progress: resolved 1065, reused 331, downloaded 0, added 0
Progress: resolved 1065, reused 763, downloaded 0, added 0
Progress: resolved 1065, reused 1004, downloaded 0, added 0
Progress: resolved 1065, reused 1049, downloaded 0, added 0, done
.../@opensumi/vscode-ripgrep postinstall$ node ./lib/postinstall.js
.../core-js@2.6.12/node_modules/core-js postinstall$ node -e "try{require('./postinstall')}catch(e){}"
.../node_modules/drivelist install$ prebuild-install || node-gyp rebuild
.../node_modules/@parcel/watcher install$ node-gyp-build
.../core-js@2.6.12/node_modules/core-js postinstall: Done
.../@opensumi/vscode-ripgrep postinstall: Using cached download: C:\Users\zhengtao\Desktop\test_softwave\ide-electron\node_modules\.pnpm\@opensumi+vscode-ripgrep@1.4.0\node_modules\@opensumi\vscode-ripgrep\bin\rg.exe
.../@opensumi/vscode-ripgrep postinstall: Done
.../keytar@7.9.0/node_modules/keytar install$ prebuild-install || npm run build
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install$ node-gyp rebuild
.../node_modules/lzma-native install$ node-gyp-build
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: C:\Users\zhengtao\Desktop\test_softwave\ide-electron\node_modules\.pnpm\nsfw@2.2.0\node_modules\nsfw>if not defined npm_config_node_gyp (node "C:\Users\zhengtao\AppData\Roaming\npm\node_modules\pnpm\dist\node-gyp-bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\zhengtao\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\bin\node-gyp.js" rebuild )
.../node_modules/@parcel/watcher install: Done
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info it worked if it ends with ok
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info using node-gyp@8.4.1
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info using node@12.22.0 | win32 | x64
.../spdlog@0.9.0/node_modules/spdlog install$ node-gyp rebuild
.../spdlog@0.9.0/node_modules/spdlog install: C:\Users\zhengtao\Desktop\test_softwave\ide-electron\node_modules\.pnpm\spdlog@0.9.0\node_modules\spdlog>if not defined npm_config_node_gyp (node "C:\Users\zhengtao\AppData\Roaming\npm\node_modules\pnpm\dist\node-gyp-bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\zhengtao\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\bin\node-gyp.js" rebuild )
.../node_modules/lzma-native install: Done
.../spdlog@0.9.0/node_modules/spdlog install: gyp info it worked if it ends with ok
.../spdlog@0.9.0/node_modules/spdlog install: gyp info using node-gyp@8.4.1
.../spdlog@0.9.0/node_modules/spdlog install: gyp info using node@12.22.0 | win32 | x64
.../keytar@7.9.0/node_modules/keytar install: Done
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info find Python using Python version 3.7.4 found at "C:\Users\zhengtao\AppData\Local\Programs\Python\Python37\python.exe"
.../spdlog@0.9.0/node_modules/spdlog install: gyp info find Python using Python version 3.7.4 found at "C:\Users\zhengtao\AppData\Local\Programs\Python\Python37\python.exe"
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info find VS using VS2015 (14.0) found at:
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info find VS run with --verbose for detailed information
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn C:\Users\zhengtao\AppData\Local\Programs\Python\Python37\python.exe
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args [
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   'C:\\Users\\zhengtao\\AppData\\Roaming\\npm\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\gyp\\gyp_main.py',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   'binding.gyp',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   '-f',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   'msvs',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   '-I',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   'C:\\Users\\zhengtao\\Desktop\\test_softwave\\ide-electron\\node_modules\\.pnpm\\nsfw@2.2.0\\node_modules\\nsfw\\build\\config.gypi',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   '-I',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   'C:\\Users\\zhengtao\\AppData\\Roaming\\npm\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\addon.gypi',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   '-I',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   'C:\\Users\\zhengtao\\AppData\\Local\\node-gyp\\Cache\\12.22.0\\include\\node\\common.gypi',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   '-Dlibrary=shared_library',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   '-Dvisibility=default',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   '-Dnode_root_dir=C:\\Users\\zhengtao\\AppData\\Local\\node-gyp\\Cache\\12.22.0',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\zhengtao\\AppData\\Roaming\\npm\\node_modules\\pnpm\\dist\\node_modules\\node-gyp',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\zhengtao\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.22.0\\\\<(target_arch)\\\\node.lib',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\zhengtao\\Desktop\\test_softwave\\ide-electron\\node_modules\\.pnpm\\nsfw@2.2.0\\node_modules\\nsfw',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   '-Dnode_engine=v8',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   '--depth=.',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   '--no-parallel',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   '--generator-output',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   'C:\\Users\\zhengtao\\Desktop\\test_softwave\\ide-electron\\node_modules\\.pnpm\\nsfw@2.2.0\\node_modules\\nsfw\\build',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   '-Goutput_dir=.'
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args ]
.../spdlog@0.9.0/node_modules/spdlog install: gyp info find VS using VS2015 (14.0) found at:
.../spdlog@0.9.0/node_modules/spdlog install: gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
.../spdlog@0.9.0/node_modules/spdlog install: gyp info find VS run with --verbose for detailed information
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn C:\Users\zhengtao\AppData\Local\Programs\Python\Python37\python.exe
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args [
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   'C:\\Users\\zhengtao\\AppData\\Roaming\\npm\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\gyp\\gyp_main.py',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   'binding.gyp',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   '-f',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   'msvs',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   '-I',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   'C:\\Users\\zhengtao\\Desktop\\test_softwave\\ide-electron\\node_modules\\.pnpm\\spdlog@0.9.0\\node_modules\\spdlog\\build\\config.gypi',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   '-I',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   'C:\\Users\\zhengtao\\AppData\\Roaming\\npm\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\addon.gypi',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   '-I',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   'C:\\Users\\zhengtao\\AppData\\Local\\node-gyp\\Cache\\12.22.0\\include\\node\\common.gypi',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   '-Dlibrary=shared_library',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   '-Dvisibility=default',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   '-Dnode_root_dir=C:\\Users\\zhengtao\\AppData\\Local\\node-gyp\\Cache\\12.22.0',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\zhengtao\\AppData\\Roaming\\npm\\node_modules\\pnpm\\dist\\node_modules\\node-gyp',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\zhengtao\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.22.0\\\\<(target_arch)\\\\node.lib',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\zhengtao\\Desktop\\test_softwave\\ide-electron\\node_modules\\.pnpm\\spdlog@0.9.0\\node_modules\\spdlog',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   '-Dnode_engine=v8',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   '--depth=.',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   '--no-parallel',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   '--generator-output',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   'C:\\Users\\zhengtao\\Desktop\\test_softwave\\ide-electron\\node_modules\\.pnpm\\spdlog@0.9.0\\node_modules\\spdlog\\build',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   '-Goutput_dir=.'
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args ]
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args [
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   'build/binding.sln',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   '/clp:Verbosity=minimal',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   '/nologo',
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args   '/p:Configuration=Release;Platform=x64'
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp info spawn args ]
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args [
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   'build/binding.sln',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   '/clp:Verbosity=minimal',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   '/nologo',
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args   '/p:Configuration=Release;Platform=x64'
.../spdlog@0.9.0/node_modules/spdlog install: gyp info spawn args ]
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: 在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
.../spdlog@0.9.0/node_modules/spdlog install: 在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\zhengtao\Desktop\test_softwave\ide-electron\node_modules\.pnpm\nsfw@2.2.0\node_modules\nsfw\build\nsfw.vcxproj]
.../spdlog@0.9.0/node_modules/spdlog install: C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\zhengtao\Desktop\test_softwave\ide-electron\node_modules\.pnpm\spdlog@0.9.0\node_modules\spdlog\build\spdlog.vcxproj]
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install:   TRACKER : 错误 TRK0005: 未能找到: “CL.exe”。系统找不到指定的文件。
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install:
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install:
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(355,5): error MSB6006: “CL.exe”已退出，代码为 5。 [C:\Users\zhengtao\Desktop\test_softwave\ide-electron\node_modules\.pnpm\nsfw@2.2.0\node_modules\nsfw\build\nsfw.vcxproj]
.../spdlog@0.9.0/node_modules/spdlog install:   TRACKER : 错误 TRK0005: 未能找到: “CL.exe”。系统找不到指定的文件。
.../spdlog@0.9.0/node_modules/spdlog install:
.../spdlog@0.9.0/node_modules/spdlog install:
.../spdlog@0.9.0/node_modules/spdlog install: C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(355,5): error MSB6006: “CL.exe”已退出，代码为 5。 [C:\Users\zhengtao\Desktop\test_softwave\ide-electron\node_modules\.pnpm\spdlog@0.9.0\node_modules\spdlog\build\spdlog.vcxproj]
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp ERR! build error
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp ERR! stack     at ChildProcess.onExit (C:\Users\zhengtao\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\lib\build.js:194:23)
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp ERR! System Windows_NT 6.1.7601
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\zhengtao\\AppData\\Roaming\\npm\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp ERR! cwd C:\Users\zhengtao\Desktop\test_softwave\ide-electron\node_modules\.pnpm\nsfw@2.2.0\node_modules\nsfw
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp ERR! node -v v12.22.0
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp ERR! node-gyp -v v8.4.1
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: gyp ERR! not ok
.../.pnpm/nsfw@2.2.0/node_modules/nsfw install: Failed
 ELIFECYCLE  Command failed with exit code 1.

**Comment by yantze** [comment]
要装一下 Visual Studio  2019 ，https://opensumi.com/zh/docs/develop/how-to-contribute => 安装 Windows Build Tools 章节

**Comment by zt6991** [comment]
安装了vs2017后，安装依赖问题解决了。但在打包的时候 运行pack.js，报了没找到fs模块的错误。

$ node build/pack.js
Error: Cannot find module 'fs/promises'
Require stack:
- C:\Users\zhengtao\Desktop\test_softwave\ide-electron\node_modules\.pnpm\builde
r-util@23.3.3\node_modules\builder-util\out\fs.js
- C:\Users\zhengtao\Desktop\test_softwave\ide-electron\node_modules\.pnpm\builde
r-util@23.3.3\node_modules\builder-util\out\util.js
- C:\Users\zhengtao\Desktop\test_softwave\ide-electron\node_modules\.pnpm\electr
on-builder@23.3.3\node_modules\electron-builder\out\index.js
- C:\Users\zhengtao\Desktop\test_softwave\ide-electron\build\pack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\zhengtao\Desktop\test_softwave\ide-electron\
node_modules\.pnpm\builder-util@23.3.3\node_modules\builder-util\src\fs.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\zhengtao\Desktop\test_softwave\ide-electron\
node_modules\.pnpm\builder-util@23.3.3\node_modules\builder-util\src\util.ts:25:
1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

**Comment by yantze** [comment]
Node.js 版本升到 14 及以上，这里用到了 Node.js 14 之后的特性

**Comment by zt6991** [comment]
试了下，Node.js 14 不支持win7 ,装不上。

**Comment by yantze** [comment]
Opensumi  官网也声明不支持 Windows 7 的， Electron  和 Node.js 维护中的版本都不支持 Windows 7 了。
