### ISSUE TITLE
不同视图间怎么实现交互效果

### ISSUE THREAD

**Issue by zt6991** [opensumi/ide-electron#75]
![1684743513901](https://github.com/opensumi/ide-electron/assets/46299593/9f2bdc2e-2902-45ac-946e-d1626463cfd1)
界面如图所示，想做一些界面交互效果但是不知道怎么实现。

希望做出的效果是用户选中右侧的红色部分后。底部的绿色框内的视图内容可以对应的更新。

希望可以提供一些简单可行的实现方案，谢谢

**Comment by Ricbet** [comment]
可以通过自定义命令的方式 https://opensumi.com/zh/docs/integrate/universal-integrate-case/custom-command#%E6%B3%A8%E5%86%8C%E8%87%AA%E5%AE%9A%E4%B9%89%E5%91%BD%E4%BB%A4

**Comment by Ricbet** [comment]
@zt6991

**Comment by zt6991** [comment]
好的，我学习一下自定义命令

**Comment by zt6991** [comment]
https://opensumi.com/zh/docs/integrate/universal-integrate-case/custom-command#%E6%B3%A8%E5%86%8C%E8%87%AA%E5%AE%9A%E4%B9%89%E5%91%BD%E4%BB%A4。
我看了下链接里的例子是在Module代码里调用的命令，如果想在在index.view.tsx调用应该怎么写代码呢？
![1684808772606](https://github.com/opensumi/ide-electron/assets/46299593/f2bc4010-a29e-4ff5-89c2-09c5e726d783)

**Comment by zt6991** [comment]
[https://opensumi.com/zh/docs/integrate/universal-integrate-case/custom-command#%E6%B3%A8%E5%86%8C%E8%87%AA%E5%AE%9A%E4%B9%89%E5%91%BD%E4%BB%A4。](https://opensumi.com/zh/docs/integrate/universal-integrate-case/custom-command#%E6%B3%A8%E5%86%8C%E8%87%AA%E5%AE%9A%E4%B9%89%E5%91%BD%E4%BB%A4%E3%80%82)
我看了下链接里的例子是在Module代码里调用命令，如果想在view里（index.view.tsx）调用命令应该怎么写代码呢？下面是我的Module代码和view代码
![0a43e923e76441d51111b3b3ebdeeb3](https://github.com/opensumi/ide-electron/assets/46299593/3b118d02-e3f4-42d1-9efc-4a703f3b7e36)
![1684809019030](https://github.com/opensumi/ide-electron/assets/46299593/222dedf8-ea4d-48b3-be81-17eda6c5e5f3)

**Comment by zt6991** [comment]
https://opensumi.com/zh/docs/integrate/universal-integrate-case/custom-command#%E6%B3%A8%E5%86%8C%E8%87%AA%E5%AE%9A%E4%B9%89%E5%91%BD%E4%BB%A4
我看了下链接里的例子代码是在Module代码里调用commandService的。但是我想在View层使用命令，我不知道代码应该咋写。下面是我的Module(index.ts)代码和View（index.view.tsx）代码
![9496a476c199581c0da7a2087342357](https://github.com/opensumi/ide-electron/assets/46299593/e082fddb-65da-4f80-9825-d81305b3e3ef)
![d02bad06ce1d856e1984d8d2a61af75](https://github.com/opensumi/ide-electron/assets/46299593/7d6a9542-717a-4c4f-abc5-586a07a3c621)

**Comment by bytemain** [comment]
参考下这个：https://github.com/opensumi/core/blob/v2.24/packages/file-tree-next/src/browser/empty.view.tsx

稍后我们更新下文档

**Comment by zt6991** [comment]
好咧，劳驾

**Comment by shileima** [comment]
@bytemain 你好, 希望同时支持electron桌面端和web版本,请问下代码是共用的吗? 是集成到一个工程还是分开两个工程比较适合二次开发?

**Comment by bytemain** [comment]
我认为在一个工程里比较合适，不同平台的代码使用条件语句来区分，也可以参考 core 里的代码：
![CleanShot 2023-12-20 at 14 54 07@2x](https://github.com/opensumi/ide-electron/assets/13938334/6240e0a6-0879-4ea1-9bfe-8f99baf9d28e)

**Comment by shileima** [comment]
> 我认为在一个工程里比较合适，不同平台的代码使用条件语句来区分，也可以参考 core 里的代码： ![CleanShot 2023-12-20 at 14 54 07@2x](https://private-user-images.githubusercontent.com/13938334/291805400-6240e0a6-0879-4ea1-9bfe-8f99baf9d28e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyOTgyOTMsIm5iZiI6MTcwMzI5Nzk5MywicGF0aCI6Ii8xMzkzODMzNC8yOTE4MDU0MDAtNjI0MGUwYTYtMDg3OS00ZWExLTliZmUtOGY5OWJhZjlkMjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDAyMTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhZDAxZTFiNGEyOGVjODlkY2IwNzcwMDI5ZjQyZmQzNTU4ZDk4MTkzZjI4ZTM5MTZhZTdjODAyYzFkNjNkODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.elI4y4cN3gA4qQw5vPNveEXZS4i5pxG35uL1PSA6vck)

如果放到一个工程里, 我使用哪个工程初始化比较好, 这个项目有融合了electron和web版的startUp吗
