### ISSUE TITLE
项目编译报错

### ISSUE THREAD

**Issue by zt6991** [opensumi/ide-electron#77]
![image](https://github.com/opensumi/ide-electron/assets/46299593/1aad13ec-041a-4c1b-a83a-a4760c4811bf)
项目编译（pnpm build）期间报错，没改过app.tsx文件。

**Comment by yantze** [comment]
看起来升级了 Opensumi 的依赖，比如把 2.22.5 升级到了 2.23.6 ？

这种升级可能需要看看新版本是否有相关接口的 bk，一般就一两个 bk，可以参考一下 bk 文档：https://github.com/opensumi/core/blob/main/CHANGELOG.md

**Comment by zt6991** [comment]
确实是Opensumi 的依赖的问题，换了下版本就好了
