### ISSUE TITLE
需要发布新的版本了，  tag 过于久远很多 bug 都没有解决，main latest 不知道稳不稳定能不能用呀

### ISSUE THREAD

**Issue by zhuzeyu22** [opensumi/ide-electron#80]
RT

**Comment by yantze** [comment]
已更新到新版 opensumi 2.24.5 ，如果 main 分支安装依赖比较慢可以试试 main-cn 分支

**Comment by zhuzeyu22** [comment]
main 和 main-cn 还是 ok 的，相对最新的 release 版本 diff 差别不大，只是依赖需要更新而已
